"use client";

import { useState, useRef, useEffect } from "react";
import { Plus, X } from "lucide-react";
import { Typography } from "../ui/typography";

type FAQItem = {
  id: string;
  question: string;
  answer: string;
};

const faqs: FAQItem[] = [
  {
    id: "001",
    question: "What is Tasmil Finance?",
    answer:
      "Tasmil Finance is an AI-powered DeFi platform built specifically for the SUI blockchain ecosystem. It serves as your smart gateway to SUI’s leading DeFi protocols, combining intelligent trading agents with seamless access to Cetus, NAVI, Bluefin, Walrus, and other major protocols through natural language interactions.",
  },
  {
    id: "002",
    question: "How does the AI agent system work?",
    answer:
      "Our AI agents act as your personal DeFi assistants. Simply describe what you want to do in natural language - like “swap 100 SUI for USDC” or “find the best yield farming opportunity” - and the agents handle the complex protocol interactions automatically. They combine real-time on-chain data with social sentiment analysis to make intelligent decisions on your behalf.",
  },
  {
    id: "003",
    question: "Is my wallet secure with Tasmil Finance?",
    answer:
      "Absolutely. Tasmil Finance uses a non-custodial, self-custody wallet architecture. Your private keys are stored locally in your browser and never leave your device. We cannot access your funds - you maintain complete control over your assets while enjoying the convenience of AI-powered DeFi interactions.",
  },
  {
    id: "004",
    question: "What makes Tasmil different from other DeFi platforms?",
    answer:
      "Tasmil is the first comprehensive AI-powered gateway specifically built for SUI’s DeFi ecosystem. Unlike traditional DeFi interfaces that require technical knowledge, our conversational agents make sophisticated strategies accessible to everyone. Plus, our creator economy lets you build and monetize your own trading agents.",
  },
  {
    id: "005",
    question: "How does the credit system and pricing work?",
    answer:
      "We offer flexible pricing with a base plan at $20/month plus credits for compute-intensive operations. You only pay additional fees when following creator agents that generate profits for you. Credits ensure priority processing and unlock advanced features like custom agent building and real-time market analysis.",
  },
  {
    id: "006",
    question: "Can I create my own trading agents?",
    answer:
      "Yes! Our no-code agent builder lets you create sophisticated DeFi strategies through simple prompts. Set your risk parameters, automation levels, and trading rules, then test your strategies in our simulation environment before deploying real capital. Successful agents can be published to our marketplace for passive revenue.",
  },
  {
    id: "007",
    question: "Which SUI protocols does Tasmil integrate with?",
    answer:
      "Tasmil directly integrates with all major SUI DeFi protocols including Cetus (DEX), NAVI (lending), Bluefin (derivatives), Walrus (storage), and many others. Our agents can execute complex multi-protocol strategies seamlessly, from yield farming to arbitrage opportunities.",
  },
  {
    id: "008",
    question: "How do I get started with Tasmil Finance?",
    answer:
      "Simply connect your SUI wallet or create a new one through our platform. Start chatting with our AI agents to explore available strategies, or browse our agent marketplace to find strategies created by other users. Your first interactions help our AI learn your preferences and risk tolerance.",
  },
  {
    id: "009",
    question: "What kind of returns can I expect?",
    answer:
      "Returns vary based on market conditions and chosen strategies. Our agents analyze real-time data to identify optimal opportunities across lending, DEX trading, yield farming, and arbitrage. Historical performance data is available for all published agents, and you can simulate strategies before committing capital.",
  },
  {
    id: "010",
    question: "How does the creator economy work?",
    answer:
      "Build profitable trading agents and earn passive income when others use them. Creators earn a percentage of profits generated by their agents, with performance-based fees ensuring alignment between creators and users. Top-performing agents get featured in our marketplace and can generate significant recurring revenue.",
  },
];



export const FAQSection = () => {
  const [openFAQ, setOpenFAQ] = useState<string>("001");
  const [heights, setHeights] = useState<Record<string, number>>({});
  const answerRefs = useRef<Record<string, HTMLDivElement | null>>({});

  // Initialize height for the default open FAQ
  useEffect(() => {
    if (openFAQ) {
      const element = answerRefs.current[openFAQ];
      if (element) {
        setHeights({
          [openFAQ]: element.scrollHeight,
        });
      }
    }
  }, []);

  const toggleFAQ = (id: string) => {
    if (openFAQ === id) {
      // Closing
      setHeights((prev) => ({ ...prev, [id]: 0 }));
      setTimeout(() => {
        setOpenFAQ("");
      }, 300); // Match this with the transition duration
    } else {
      // Opening
      const element = answerRefs.current[id];
      if (element) {
        // First set the current open one to close
        if (openFAQ) {
          setHeights((prev) => ({ ...prev, [openFAQ]: 0 }));
        }

        // Set the new one to open
        setOpenFAQ(id);

        // Need a small delay to ensure the element is in the DOM
        setTimeout(() => {
          setHeights((prev) => ({ ...prev, [id]: element.scrollHeight }));
        }, 50);
      }
    }
  };

  // Function to set a ref for a specific FAQ item
  const setAnswerRef = (id: string) => (element: HTMLDivElement | null) => {
    answerRefs.current[id] = element;
  };

  return (
    <section className="w-full bg-black">
      <div className="w-full mx-auto px-4 md:px-10 py-12 md:py-16">
        <div className="mb-12 text-center">
          <Typography
            font="labGrotesk"
            className="text-primary text-center mb-2"
            as="p"
          >
            / FAQS
          </Typography>
          <Typography
            variant="h2"
            weight="bold"
            align="center"
            className="text-embossed mb-8 text-4xl md:text-5xl"
          >
            FREQUENTLY ASKED QUESTIONS
          </Typography>
        </div>

        <div className="w-full mx-auto bg-white rounded-2xl">
          {faqs.map((faq, index) => {
            const isFirst = index === 0;
            const isLast = index === faqs.length - 1;
            const isOpen = openFAQ === faq.id;

            return (
              <div
                key={faq.id}
                className={`${!isLast || isOpen ? "border-b border-[#E5E5E5]" : ""} ${isFirst && isOpen ? "rounded-t-2xl" : ""} ${isLast && isOpen ? "rounded-b-2xl" : ""}`}
              >
                <div
                  className="flex items-center justify-between py-6 px-6 cursor-pointer"
                  onClick={() => toggleFAQ(faq.id)}
                >
                  <div className="flex items-center">
                    <Typography
                      as="span"
                      className="mr-6 font-mono text-[#9A9BA0]"
                    >
                      {faq.id}
                    </Typography>
                    <Typography
                      // variant="h3"
                      font="darkerGrotesk"
                      weight="medium"
                      className="text-black text-lg md:text-3.8xl mb-1"
                    >
                      {faq.question}
                    </Typography>
                  </div>
                  <button className="h-8 w-8 flex items-center justify-center">
                    {isOpen ? (
                      <X className="h-6 w-6 text-black transition-transform duration-300" />
                    ) : (
                      <Plus className="h-6 w-6 text-black transition-transform duration-300" />
                    )}
                  </button>
                </div>
                <div
                  className="overflow-hidden transition-all duration-300 ease-in-out"
                  style={{
                    height: heights[faq.id] || 0,
                    opacity: heights[faq.id] ? 1 : 0,
                  }}
                >
                  <div
                    ref={setAnswerRef(faq.id)}
                    className="bg-[#111111] mx-6 p-6 pl-16 pr-8 rounded-2xl mb-6"
                  >
                    <Typography
                      font="darkerGrotesk"
                      className="text-white text-lg md:text-xl"
                    >
                      {faq.answer}
                    </Typography>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
